Repository t3n/react-packages, pull requests merged in 2025-01, with the labels that each got.

#1013 feat: :sparkles: adjust user-menu to fit new ssb
  packages/components/src/UserMenu/UserMenu.d.ts
  packages/components/src/UserMenu/UserMenu.tsx
Labels: size/s

#1014 feat: allow chevron icon as button for carousel
  packages/components/src/Carousel/Carousel.d.ts
  packages/components/src/Carousel/Carousel.tsx
  packages/storybook/src/stories/components/content/carousel.stories.d.ts
  packages/storybook/src/stories/components/content/carousel.stories.tsx
Labels: enhancement, size/m

#1015 feat: remove bubble around X-button
  packages/components/src/Modal/Modal.tsx
Labels: size/s

#1016 fix: bring back cursor -> pointer
  packages/components/src/Modal/Modal.tsx
Labels: size/xs

#1017 feat: make adjustments to modal and carousel (slick-slider)
  packages/components/src/Carousel/Carousel.d.ts
  packages/components/src/Carousel/Carousel.tsx
  packages/components/src/Modal/Modal.d.ts
  packages/components/src/Modal/Modal.tsx
Labels: size/xs

#1018 feat: adjust styles for very small screens
  packages/components/src/Carousel/Carousel.tsx
  packages/components/src/Modal/Modal.tsx
Labels: size/s

#1019 feat: :sparkles: adjust navi button leading to abos page
  packages/components/src/LegacyFooter/LegacyDesktopFooter.tsx
  packages/components/src/LegacyFooter/LegacyMobileFooter.tsx
  packages/components/src/LegacyHeader/LegacyDesktopHeader.tsx
Labels: size/s

#1021 chore: add missing button stories
  packages/storybook/src/stories/components/inputs/button.stories.tsx
Labels: size/s

#1023 chore: :bug: adjust usercard component to fix hydration errors #2
  packages/components/src/UserCard/UserCard.tsx
Labels: size/s
