Repository t3n/react-packages, pull requests merged in 2025-06, with the labels that each got.

#1046 chore: :arrow_up: upgrade dependencies
  .husky/pre-commit
  .prettierignore
  package-lock.json
  package.json
  packages/components/package.json
  packages/theme/package.json
Labels: size/xl

#1048 fix: exchange LegacyBreadcrumb margin with padding to avoid ad background to show
  packages/components/src/LegacyBreadcrumb/LegacyBreadcrumb.tsx
Labels: size/xs

#1049 feat(a11y): alt texts for article teaser images
  packages/components/src/ArticleTeaser/ArticleTeaser.tsx
Labels: size/xs

#1052 feat: link to bfsg legal text in footer
  packages/components/src/PageFooter/DesktopFooter.tsx
  packages/components/src/PageFooter/MobileFooter.tsx
Labels: size/s
